---
title: "Instant Advance Mockup V1"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: menu
    theme: cerulean
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(data.table)
library(plotly)


put_risk_into_data <- function(data, fraud_risk, risk_of_suspeniosn, periods) {
  dt <- copy(data)
  
  N = 1:ncol(dt)
  rows = 1:nrow(dt)
  
  for (row in rows) {
    fraud = rbinom(n = 1, size = 1, prob = fraud_risk)
    if (fraud == 1) {
      dt[row, 1:92 := 0]
      next()
    }
    blocked = rbinom(n = 1, size = 1, prob = risk_of_suspeniosn)
    if (blocked == 1) {
      day = sample(x = 1:periods, size = 1, replace = F)
      dt[row, day:92 := 0]
    }
  }
  
  return(dt)
}
```

```{r, include=FALSE}
data = fread('data.csv')
dt_plot = fread('dt_plot.csv')

mean_m_sales = round(dt_plot[between(date, '2018-07-01', '2018-09-31'), sum(sales)/.N*30],-2)
```

Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
numericInput("ammount", "Proposed ammount", mean_m_sales, min = 0, max = 1e6)
sliderInput("suspension", label = "Suspension risk:",
            min = 0.01, max = 1, value = 0.05, step = 0.01)

sliderInput("fraud", label = "Fraud risk:",
            min = 0, max = 1, value = 0.005, step = 0.005)

sliderInput("loan", label = "Loan percent:",
            min = 0.01, max = 1, value = 0.33, step = 0.01)


```


```{r, include=FALSE}
periods = ncol(data)

results = reactive({
   dt = put_risk_into_data(data = data, fraud_risk = input$fraud, risk_of_suspeniosn = input$suspension, periods=periods)
   sales = rowSums(dt)
   sales_month = sales/ncol(dt)*30
   proposed = round(seq(from = 0.5 * input$ammount, to = 1.5 * input$ammount, length.out = 10))
   sales_share_ours = rowSums(dt * input$loan)
  
   
   dt_compare = data.table(level = as.factor(proposed))
   dt_compare[, profit := 0]
   dt_compare[, risk := 0]
   
   for (p in seq_along(proposed)) {
         prop_ = proposed[p]
         money_lended = prop_ * (1-input$loan)
         our_profit = pmin(sales_share_ours, prop_) - money_lended
         dt_compare[level == prop_, profit := round(mean(our_profit))]
         dt_compare[level == prop_, risk := mean(our_profit < 0)]
  }
  return(list(sales = sales, sales_month = sales_month, dt_compare = dt_compare))
})

 
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
  plot_ly(dt_plot) %>%
  add_lines(x = ~date, y = ~sales,
             name = "Observed sales", color = I('seagreen4')) %>% 
  add_ribbons(x = ~date, y ~ predicted, ymin = ~lower, ymax = ~upper,  color = I("gray80"),
              name = "95% confidence interval") %>% 
    layout(legend = list(x = 0.1, y = 0.9),
           xaxis = list(showgrid = F))
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r, echo = FALSE}
ay <- list(
          title = "",
          zeroline = FALSE,
          showline = FALSE,
          overlaying = "y",
          side = "right",
          showticklabels = FALSE,
          showgrid = FALSE,
          hoverformat = ',.1%'
        )

t <- list(
          family = "sans serif",
          size = 14,
          color = 'blue')

 renderPlotly({
        d = results()$dt_compare
        plot_ly(d) %>% 
        add_trace(x = ~ level, y = ~ profit, type = 'bar', text = ~ profit, name = 'Expected profit') %>% 
        add_trace(x = ~level, y = ~risk, type = 'scatter', mode = 'lines',  text = ~ risk, textposition = 'auto', color = I('brown2'), 
                   yaxis = 'y2', name= 'Risk of losing money')%>% 
        layout(
          title = list("Loan recommendation for a seller"),
          yaxis2 = ay,
          xaxis = list(title="",
                       ticksuffix = '$'),
          yaxis = list(ticksuffix = '$'),
          legend = list(orientation = 'h')
        )
})


```


### Chart C
```{r}
renderPlotly({plot_ly(alpha = 0.6) %>%
  add_histogram(x = results()$sales_month, color = I('darkorange4'))})
```


